version: '3.8'
services:

  foodgram_db:
    container_name: foodgram_db
    image: postgres:13.0-alpine
    volumes:
      - db_volume:/var/lib/postgresql/data/
    env_file:
      ./.env

  foodgram_backend:
    container_name: foodgram_backend
    image: ${DOCKER_USERNAME}/foodgram_backend:v1.0
    restart: always
    volumes:
      - static_data:/app/static/
      - media_data:/app/media/
    depends_on:
      - foodgram_db
    env_file:
      ./.env

  foodgram_frontend:
    container_name: foodgram_frontend
    image: ${DOCKER_USERNAME}/foodgram_frontend:v1.0
    volumes:
      - frontend/:/app/result_build/

  foodgram_nginx:
    container_name: foodgram_nginx
    image: nginx:1.19.3
    ports:
     - "80:80"
    volumes:
      - static_data:/var/html/static/
      - media_data:/var/html/media/
      - frontend:/usr/share/nginx/html/
      - ./nginx/foodgram.conf:/etc/nginx/conf.d/default.conf
      - ./foodgram_docs:/usr/share/nginx/html/api/docs/
    depends_on:
      - foodgram_frontend
      - foodgram_backend

volumes:
  static_data:
    name: static_data
  media_data:
    name: media_data
  frontend:
    name: frontend
  db_volume:
    name: db_volume
